       DEF  LTEST
       REF  LOADER,VMBW,VSBW

* Use this program in order to load all
* of the files needed to run the word 
* processor.

FILES  DATA FILEN1,FILEN2,FILEN3,FILEN4
       DATA FILEN5,FILEN6,FILEN7,FILEN8
       DATA FILEN9,FILENA,FILENB,FILENC
       DATA FILEND,FILENE
	   DATA LSTEND
PDATAE
FILEN1 TEXT 'DSK2.MAIN.obj'
FILEN2 TEXT 'DSK2.CONST.obj'
FILEN3 TEXT 'DSK2.MEMBUF.obj'
FILEN4 TEXT 'DSK2.ARRAY.obj'
FILEN5 TEXT 'DSK2.INPUT.obj'
FILEN6 TEXT 'DSK2.WRAP.obj'
FILEN7 TEXT 'DSK2.POSUPD.obj'
FILEN8 TEXT 'DSK2.DISP.obj'
FILEN9 TEXT 'DSK2.KEY.obj'
FILENA TEXT 'DSK2.VDP.obj'
FILENB TEXT 'DSK2.LOOK.obj'
FILENC TEXT 'DSK2.ACT.obj'
FILEND TEXT 'DSK2.VAR.obj'
FILENE TEXT 'DSK2.END.obj'
LSTEND TEXT ' '
       EVEN
	   
       COPY "DSK2.LOADTSTS.asm"