       DEF  LTEST
       REF  LOADER,VMBW,VSBW

* Use this program in order to load all
* of the files needed to test WRAP.
* It will execute the WRAP tests
* automatically.

FILES  DATA FILEN1,FILEN2,FILEN3,FILEN4
       DATA FILEN5,FILEN6,FILEN7,LSTEND
PDATAE
FILEN1 TEXT 'DSK2.TESTFRAM.obj'
FILEN2 TEXT 'DSK2.WRAPTST.obj'
FILEN3 TEXT 'DSK2.WRAP.obj'
FILEN4 TEXT 'DSK2.MEMBUF.obj'
FILEN5 TEXT 'DSK2.VAR.obj'
FILEN6 TEXT 'DSK2.CONST.obj'
FILEN7 TEXT 'DSK2.ARRAY.obj'
LSTEND TEXT ' '
       EVEN

       COPY "DSK2.LOADTSTS.asm"